version: '3.8'
services:
  app:
    image: spring-board-image-hoon
    build:
      context: ./docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev